Add missing files

diff --git a/.local/bin/passmenu b/.local/bin/passmenu
--- a/.local/bin/passmenu
+++ b/.local/bin/passmenu
@@ -8,14 +8,10 @@ if [[ $1 == "--type" ]]; then
 	shift
 fi
 
-if [[ -n $WAYLAND_DISPLAY ]]; then
-	dmenu=dmenu-wl
-	xdotool="ydotool type --file -"
-elif [[ -n $DISPLAY ]]; then
-	dmenu=dmenu
+if [[ -n $DISPLAY ]]; then
 	xdotool="xdotool type --clearmodifiers --file -"
 else
-	echo "Error: No Wayland or X11 display detected" >&2
+	echo "Error: No X11 display detected" >&2
 	exit 1
 fi
 
@@ -24,7 +20,7 @@ password_files=( "$prefix"/!(**-otp)/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
+password=$(printf '%s\n' "${password_files[@]}" | dmenusty "$@")
 
 [[ -n $password ]] || exit
 
